endpoint_config_base_location: "/var/www/html"
date_service_uri: "http://137.79.29.45:8090/date"
target_epsg_code: "EPSG:3857"
source_gc_uri: "https://gibs.earthdata.nasa.gov/wmts/epsg4326/best/1.0.0/WMTSCapabilities.xml"
tms_defs_file: "/etc/oe2/tilematrixsets.xml"
gc_service_uri: "/gc_service_test_gc_header_equal"
include_layers: 
  - 'AMSR2_Cloud_Liquid_Water_Day'
  - 'AMSR2_Cloud_Liquid_Water_Night'
layer_config_source: layer_config.yaml
apache_config_location: /etc/httpd/conf.d/oe2-test_gc.conf
external_endpoint: '/dingus'
base_uri_gc: 'sower'