time_service_uri: "http://onearth-time-service/time_service/time"
time_service_keys: ["epsg4326", "all"]
gc_service_uri: "/wmts/epsg4326/all/gc"
tms_defs_file: "/etc/onearth/config/conf/tilematrixsets.xml"
layer_config_source: "/etc/onearth/config/layers/epsg4326/all/"
apache_config_location: "/etc/httpd/conf.d/"
base_uri_gc: "http://localhost/wmts/epsg4326/all/"
base_uri_gts: "http://localhost/wmts/epsg4326/all/"
epsg_code: "EPSG:4326"
gc_service:
  internal_endpoint: "/var/www/html/wmts/epsg4326/all"
  external_endpoint: "/wmts/epsg4326/all/gc"
  config_prefix: "epsg4326_all_gc_service"
  gc_header_file: "/etc/onearth/config/conf/header_gc.xml"
  gts_header_file: "/etc/onearth/config/conf/header_gts.xml"
  twms_gc_header_file: "/etc/onearth/config/conf/header_twms_gc.xml"
wmts_service:
  internal_endpoint: "/var/www/html/wmts/epsg4326/all"
  external_endpoint: "/wmts/epsg4326/all"
  config_prefix: "epsg4326_all"
twms_service:
  internal_endpoint: "/var/www/html/wmts/epsg4326/all"
  external_endpoint: "/wmts/epsg4326/all"