source_gc_uri: "http://localhost/wmts/epsg4326/best/1.0.0/WMTSCapabilities.xml"
time_service_uri: "http://onearth-time-service/time_service/time"
time_service_keys: ["epsg3857", "best"]
gc_service_uri: "/wmts/epsg3857/best/gc"
tms_defs_file: "/etc/onearth/config/conf/tilematrixsets.xml"
layer_config_source: "/etc/onearth/config/layers/epsg4326/"
apache_config_location: "/etc/httpd/conf.d/"
base_uri_gc: "http://localhost/wmts/epsg3857/best/"
base_uri_gts: "http://localhost/wmts/epsg3857/best/"
epsg_code: "EPSG:4326"
target_epsg_code: "EPSG:3857"
gc_service:
  internal_endpoint: "/var/www/html/wmts/epsg3857/best"
  external_endpoint: "/wmts/epsg3857/best/gc"
  config_prefix: "epsg3857_best_gc_service"
  gc_header_file: "/etc/onearth/config/conf/header_gc.xml"
  gts_header_file: "/etc/onearth/config/conf/header_gts.xml"
  twms_gc_header_file: "/etc/onearth/config/conf/header_twms_gc.xml"
wmts_service:
  internal_endpoint: "/var/www/html/wmts/epsg3857/best"
  external_endpoint: "/wmts/epsg3857/best"
  config_prefix: "epsg3857_best"
twms_service:
  internal_endpoint: "/var/www/html/wmts/epsg3857/best"
  external_endpoint: "/wmts/epsg3857/best"