time_service_uri: "http://onearth-time-service/time_service/time"
time_service_keys: ["epsg3031", "all"]
tms_defs_file: "/etc/onearth/config/conf/tilematrixsets.xml"
gc_header_file: "/etc/onearth/config/conf/header_gc.xml"
gts_header_file: "/etc/onearth/config/conf/header_gts.xml"
layer_config_source: "/etc/onearth/config/layers/epsg3031/all/"
apache_config_location: "/etc/httpd/conf.d/oe2_epsg3031_all.conf"
endpoint_config_base_location: "/var/www/html/wmts/epsg3031/all"
base_uri_gc: "http://localhost/wmts/epsg3031/all/"
base_uri_gts: "http://localhost/twms/epsg3031/all/"
epsg_code: "EPSG:3031"
gc_endpoint: "1.0.0"
gts_endpoint: ""
target_epsg_code: "EPSG:3031"
