time_service_uri: "http://onearth-time-service/time_service/time"
time_service_keys: ["epsg4326", "std"]
gc_service_uri: "/epsg4326/std/gc"
tms_defs_file: "/etc/onearth/config/conf/tilematrixsets.xml"
layer_config_source: "/etc/onearth/config/layers/epsg4326/std/"
apache_config_location: "/etc/httpd/conf.d/epsg4326_std.conf"
base_uri_gc: "http://localhost/epsg4326/std/"
base_uri_gts: "http://localhost/epsg4326/std/"
epsg_code: "EPSG:4326"
gc_service:
  internal_endpoint: "/var/www/html/epsg4326/std"
  external_endpoint: "/epsg4326/std/gc"
  config_prefix: "epsg4326_std_gc_service"
  gc_header_file: "/etc/onearth/config/conf/header_gc.xml"
  gts_header_file: "/etc/onearth/config/conf/header_gts.xml"
  twms_gc_header_file: "/etc/onearth/config/conf/header_twms_gc.xml"
wmts_service:
  internal_endpoint: "/var/www/html/epsg4326/std"
  external_endpoint: "/epsg4326/std"
  config_prefix: "epsg4326_std"
twms_service:
  internal_endpoint: "/var/www/html/epsg4326/std"
  external_endpoint: "/epsg4326/std"