date_service_uri: "http://localhost/date_service/date"
tms_defs_file: "/etc/onearth/config/conf/tilematrixsets.xml"
gc_header_file: "/etc/onearth/config/conf/header_gc.xml"
gts_header_file: "/etc/onearth/config/conf/header_gts.xml"
layer_config_source: "/etc/onearth/layers/layer_config.yaml"
apache_config_location: "/etc/httpd/conf.d/gc.conf"
endpoint_config_base_location: "/var/www/html"
base_uri_gc: "https://gibs.earthdata.nasa.gov/wmts/epsg4326/best/"
base_uri_gts: "https://gibs.earthdata.nasa.gov/twms/epsg4326/best/"
epsg_code: "EPSG:4326"
gc_endpoint: "/gc"
gts_endpoint: "/gts"
target_epsg_code: "EPSG:3857"
