date_service_uri: "date_service"
tms_defs_file: "/etc/onearth/tilematrixsets.xml"
gc_header_file: "/etc/onearth/headers/header_gc.xml"
gts_header_file: "/etc/onearth/headers/header_gts.xml"
layer_config_source: "/tmp/layer_config.yaml"
apache_config_location: "/etc/httpd/conf.d/gc.conf"
endpoint_config_base_location: "/var/www/html"
base_uri_gc: "https://gibs.earthdata.nasa.gov/wmts/epsg4326/best/"
base_uri_gts: "https://gibs.earthdata.nasa.gov/twms/epsg4326/best/"
epsg_code: "EPSG:4326"
gc_endpoint: "/gc"
gts_endpoint: "/gts"