date_service_uri: "http://192.168.1.142:8090/date"
tms_defs_file: "tms/EPSG4326.xml"
gc_header_file: "tms/header.xml"
layer_config_source: "configs/"
apache_config_location: "/etc/httpd/conf.d/gc.conf"
endpoint_config_base_location: "/var/www/html"
gts_header_file: "header_gts.xml"
base_uri_gc: "https://gibs.earthdata.nasa.gov/wmts/epsg4326/best/"
base_uri_gts: "https://gibs.earthdata.nasa.gov/twms/epsg4326/best/"